/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestAssured_Batch19April;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
